services:
  - type: web
    name: portfolio-laravel
    env: docker
    branch: main
    dockerfilePath: Dockerfile
    plan: starter
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://portfolio-laravel.onrender.com
